import sys
import os
from os import system



system("title "+"SePy Beta")
try:

    print('''
 .d8888b.         8888888b.          
d88P  Y88b        888   Y88b         
Y88b.             888    888         
 "Y888b.   .d88b. 888   d88P888  888 
    "Y88b.d8P  Y8b8888888P" 888  888 
      Created by Erdi       888  888 
Y88b  d88PY8b.    888       Y88b 888 
 "Y8888P"  "Y8888 888        "Y88888 
                                 888 
                            Y8b d88P 
                             "Y88P" 
''')

    victimName = input("->Kurbanın Adı: ")
    data = open(victimName + '.txt','a+')
    print ('[!] Her bilgi satırına tek bir kelime yazılır')
    print('[!] Örnek Bilgi: Kars')
    a = input('->Bilgi 1 : ')
    b = input('->Bilgi 2 : ')
    c = input('->Bilgi 3 : ')
    d = input('->Bilgi 4 : ')
    e = input('->Bilgi 5 : ')
    f = input('->Bilgi 6 : ')
    g = input('->Bilgi 7 : ')
    h = input('->Bilgi 8 : ')
    i = input('->Bilgi 9 : ')
    j = input('->Bilgi 10 : ')
    birthday = input("->Doğum Tarihi (GG.AA.YY): ")
    while len(birthday) != 0 and len(birthday) != 8 or len(birthday) == 0:
	    print("\n[-] Doğum tarihi hatalı bir biçimde yazıldı")
	    birthday = input("->Doğum Tarihi (GG.AA.YY): ")
    ### The real painful shit starts here ###
    data.write(a)
    data.write('\n')
    data.write(b)
    data.write('\n')
    data.write(c)
    data.write('\n')
    data.write(d)
    data.write('\n')
    data.write(e)
    data.write('\n')
    data.write(f)
    data.write('\n')
    data.write(g)
    data.write('\n')
    data.write(h)
    data.write('\n')
    data.write(i)
    data.write('\n')
    data.write(j)
    data.write(birthday + victimName)
    data.write('\n')
    data.write(victimName.title() + birthday)
    data.write('\n')
    data.write(victimName + birthday)
    data.write('\n')
    data.write(birthday)
    data.write('\n')
    data.write(victimName)
    data.write('\n')
    data.write(a + a)
    data.write('\n')
    data.write(a + b)
    data.write('\n')
    data.write(a + c)
    data.write('\n')
    data.write(a + d)
    data.write('\n')
    data.write(a + e)
    data.write('\n')
    data.write(a + f)
    data.write('\n')
    data.write(a + g)
    data.write('\n')
    data.write(a + h)
    data.write('\n')
    data.write(a + i)
    data.write('\n')
    data.write(a + j)
    data.write('\n')
    data.write(b + a)
    data.write('\n')
    data.write(b + b)
    data.write('\n')
    data.write(b + c)
    data.write('\n')
    data.write(b + d)
    data.write('\n')
    data.write(b + e)
    data.write('\n')
    data.write(b + f)
    data.write('\n')
    data.write(b + g)
    data.write('\n')
    data.write(b + h)
    data.write('\n')
    data.write(b + i)
    data.write('\n')
    data.write(b + j)
    data.write('\n')
    data.write(c + a)
    data.write('\n')
    data.write(c + b)
    data.write('\n')
    data.write(c + c)
    data.write('\n')
    data.write(c + d)
    data.write('\n')
    data.write(c + e)
    data.write('\n')
    data.write(c + f)
    data.write('\n')
    data.write(c + g)
    data.write('\n')
    data.write(c + h)
    data.write('\n')
    data.write(c + i)
    data.write('\n')
    data.write(c + j)
    data.write('\n')
    data.write(d + a)
    data.write('\n')
    data.write(d + b)
    data.write('\n')
    data.write(d + c)
    data.write('\n')
    data.write(d + d)
    data.write('\n')
    data.write(d + e)
    data.write('\n')
    data.write(d + f)
    data.write('\n')
    data.write(d + g)
    data.write('\n')
    data.write(d + h)
    data.write('\n')
    data.write(d + i)
    data.write('\n')
    data.write(d + j)
    data.write('\n')
    data.write(e + a)
    data.write('\n')
    data.write(e + b)
    data.write('\n')
    data.write(e + c)
    data.write('\n')
    data.write(e + d)
    data.write('\n')
    data.write(e + e)
    data.write('\n')
    data.write(e + f)
    data.write('\n')
    data.write(e + g)
    data.write('\n')
    data.write(e + h)
    data.write('\n')
    data.write(e + i)
    data.write('\n')
    data.write(e + j)
    data.write('\n')
    data.write(f + a)
    data.write('\n')
    data.write(f + b)
    data.write('\n')
    data.write(f + c)
    data.write('\n')
    data.write(f + d)
    data.write('\n')
    data.write(f + e)
    data.write('\n')
    data.write(f + f)
    data.write('\n')
    data.write(f + g)
    data.write('\n')
    data.write(f + h)
    data.write('\n')
    data.write(f + i)
    data.write('\n')
    data.write(f + j)
    data.write('\n')
    data.write(g + a)
    data.write('\n')
    data.write(g + b)
    data.write('\n')
    data.write(g + c)
    data.write('\n')
    data.write(g + d)
    data.write('\n')
    data.write(g + e)
    data.write('\n')
    data.write(g + f)
    data.write('\n')
    data.write(g + g)
    data.write('\n')
    data.write(g + h)
    data.write('\n')
    data.write(g + i)
    data.write('\n')
    data.write(g + j)
    data.write('\n')
    data.write(h + a)
    data.write('\n')
    data.write(h + b)
    data.write('\n')
    data.write(h + c)
    data.write('\n')
    data.write(h + d)
    data.write('\n')
    data.write(h + e)
    data.write('\n')
    data.write(h + f)
    data.write('\n')
    data.write(h + g)
    data.write('\n')
    data.write(h + h)
    data.write('\n')
    data.write(h + i)
    data.write('\n')
    data.write(h + j)
    data.write('\n')
    data.write(i + a)
    data.write('\n')
    data.write(i + b)
    data.write('\n')
    data.write(i + c)
    data.write('\n')
    data.write(i + d)
    data.write('\n')
    data.write(i + e)
    data.write('\n')
    data.write(i + f)
    data.write('\n')
    data.write(i + g)
    data.write('\n')
    data.write(i + h)
    data.write('\n')
    data.write(i + i)
    data.write('\n')
    data.write(i + j)
    data.write('\n')
    data.write(j + a)
    data.write('\n')
    data.write(j + b)
    data.write('\n')
    data.write(j + c)
    data.write('\n')
    data.write(j + d)
    data.write('\n')
    data.write(j + e)
    data.write('\n')
    data.write(j + f)
    data.write('\n')
    data.write(j + g)
    data.write('\n')
    data.write(j + h)
    data.write('\n')
    data.write(j + i)
    data.write('\n')
    data.write(j + j)
    data.write('\n')
    data.write(a + a + b)
    data.write('\n')
    data.write(a + a + c)
    data.write('\n')
    data.write(a + a + d)
    data.write('\n')
    data.write(a + a + e)
    data.write('\n')
    data.write(a + a + f)
    data.write('\n')
    data.write(a + a + g)
    data.write('\n')
    data.write(a + a + h)
    data.write('\n')
    data.write(a + a + i)
    data.write('\n')
    data.write(a + a + j)
    data.write('\n')
    data.write(a + b + a)
    data.write('\n')
    data.write(a + b + b)
    data.write('\n')
    data.write(a + b + c)
    data.write('\n')
    data.write(a + b + d)
    data.write('\n')
    data.write(a + b + e)
    data.write('\n')
    data.write(a + b + f)
    data.write('\n')
    data.write(a + b + g)
    data.write('\n')
    data.write(a + b + h)
    data.write('\n')
    data.write(a + b + i)
    data.write('\n')
    data.write(a + b + j)
    data.write('\n')
    data.write(a + c + a)
    data.write('\n')
    data.write(a + c + b)
    data.write('\n')
    data.write(a + c + c)
    data.write('\n')
    data.write(a + c + d)
    data.write('\n')
    data.write(a + c + e)
    data.write('\n')
    data.write(a + c + f)
    data.write('\n')
    data.write(a + c + g)
    data.write('\n')
    data.write(a + c + h)
    data.write('\n')
    data.write(a + c + i)
    data.write('\n')
    data.write(a + c + j)
    data.write('\n')
    data.write(a + d + a)
    data.write('\n')
    data.write(a + d + b)
    data.write('\n')
    data.write(a + d + c)
    data.write('\n')
    data.write(a + d + d)
    data.write('\n')
    data.write(a + d + e)
    data.write('\n')
    data.write(a + d + f)
    data.write('\n')
    data.write(a + d + g)
    data.write('\n')
    data.write(a + d + h)
    data.write('\n')
    data.write(a + d + i)
    data.write('\n')
    data.write(a + d + j)
    data.write('\n')
    data.write(a + e + a)
    data.write('\n')
    data.write(a + e + b)
    data.write('\n')
    data.write(a + e + c)
    data.write('\n')
    data.write(a + e + d)
    data.write('\n')
    data.write(a + e + e)
    data.write('\n')
    data.write(a + e + f)
    data.write('\n')
    data.write(a + e + g)
    data.write('\n')
    data.write(a + e + h)
    data.write('\n')
    data.write(a + e + i)
    data.write('\n')
    data.write(a + e + j)
    data.write('\n')
    data.write(a + f + a)
    data.write('\n')
    data.write(a + f + b)
    data.write('\n')
    data.write(a + f + c)
    data.write('\n')
    data.write(a + f + d)
    data.write('\n')
    data.write(a + f + e)
    data.write('\n')
    data.write(a + f + f)
    data.write('\n')
    data.write(a + f + g)
    data.write('\n')
    data.write(a + f + h)
    data.write('\n')
    data.write(a + f + i)
    data.write('\n')
    data.write(a + f + j)
    data.write('\n')
    data.write(a + g + a)
    data.write('\n')
    data.write(a + g + b)
    data.write('\n')
    data.write(a + g + c)
    data.write('\n')
    data.write(a + g + d)
    data.write('\n')
    data.write(a + g + e)
    data.write('\n')
    data.write(a + g + f)
    data.write('\n')
    data.write(a + g + g)
    data.write('\n')
    data.write(a + g + h)
    data.write('\n')
    data.write(a + g + i)
    data.write('\n')
    data.write(a + g + j)
    data.write('\n')
    data.write(a + h + a)
    data.write('\n')
    data.write(a + h + b)
    data.write('\n')
    data.write(a + h + c)
    data.write('\n')
    data.write(a + h + d)
    data.write('\n')
    data.write(a + h + e)
    data.write('\n')
    data.write(a + h + f)
    data.write('\n')
    data.write(a + h + g)
    data.write('\n')
    data.write(a + h + h)
    data.write('\n')
    data.write(a + h + i)
    data.write('\n')
    data.write(a + h + j)
    data.write('\n')
    data.write(a + i + a)
    data.write('\n')
    data.write(a + i + b)
    data.write('\n')
    data.write(a + i + c)
    data.write('\n')
    data.write(a + i + d)
    data.write('\n')
    data.write(a + i + e)
    data.write('\n')
    data.write(a + i + f)
    data.write('\n')
    data.write(a + i + g)
    data.write('\n')
    data.write(a + i + h)
    data.write('\n')
    data.write(a + i + i)
    data.write('\n')
    data.write(a + i + j)
    data.write('\n')
    data.write(a + j + a)
    data.write('\n')
    data.write(a + j + b)
    data.write('\n')
    data.write(a + j + c)
    data.write('\n')
    data.write(a + j + d)
    data.write('\n')
    data.write(a + j + e)
    data.write('\n')
    data.write(a + j + f)
    data.write('\n')
    data.write(a + j + g)
    data.write('\n')
    data.write(a + j + h)
    data.write('\n')
    data.write(a + j + i)
    data.write('\n')
    data.write(a + j + j)
    data.write('\n')
    data.write(b + a + b)
    data.write('\n')
    data.write(b + a + c)
    data.write('\n')
    data.write(b + a + d)
    data.write('\n')
    data.write(b + a + e)
    data.write('\n')
    data.write(b + a + f)
    data.write('\n')
    data.write(b + a + g)
    data.write('\n')
    data.write(b + a + h)
    data.write('\n')
    data.write(b + a + i)
    data.write('\n')
    data.write(b + a + j)
    data.write('\n')
    data.write(b + b + a)
    data.write('\n')
    data.write(b + b + b)
    data.write('\n')
    data.write(b + b + c)
    data.write('\n')
    data.write(b + b + d)
    data.write('\n')
    data.write(b + b + e)
    data.write('\n')
    data.write(b + b + f)
    data.write('\n')
    data.write(b + b + g)
    data.write('\n')
    data.write(b + b + h)
    data.write('\n')
    data.write(b + b + i)
    data.write('\n')
    data.write(b + b + j)
    data.write('\n')
    data.write(b + c + a)
    data.write('\n')
    data.write(b + c + b)
    data.write('\n')
    data.write(b + c + c)
    data.write('\n')
    data.write(b + c + d)
    data.write('\n')
    data.write(b + c + e)
    data.write('\n')
    data.write(b + c + f)
    data.write('\n')
    data.write(b + c + g)
    data.write('\n')
    data.write(b + c + h)
    data.write('\n')
    data.write(b + c + i)
    data.write('\n')
    data.write(b + c + j)
    data.write('\n')
    data.write(b + d + a)
    data.write('\n')
    data.write(b + d + b)
    data.write('\n')
    data.write(b + d + c)
    data.write('\n')
    data.write(b + d + d)
    data.write('\n')
    data.write(b + d + e)
    data.write('\n')
    data.write(b + d + f)
    data.write('\n')
    data.write(b + d + g)
    data.write('\n')
    data.write(b + d + h)
    data.write('\n')
    data.write(b + d + i)
    data.write('\n')
    data.write(b + d + j)
    data.write('\n')
    data.write(b + e + a)
    data.write('\n')
    data.write(b + e + b)
    data.write('\n')
    data.write(b + e + c)
    data.write('\n')
    data.write(b + e + d)
    data.write('\n')
    data.write(b + e + e)
    data.write('\n')
    data.write(b + e + f)
    data.write('\n')
    data.write(b + e + g)
    data.write('\n')
    data.write(b + e + h)
    data.write('\n')
    data.write(b + e + i)
    data.write('\n')
    data.write(b + e + j)
    data.write('\n')
    data.write(b + f + a)
    data.write('\n')
    data.write(b + f + b)
    data.write('\n')
    data.write(b + f + c)
    data.write('\n')
    data.write(b + f + d)
    data.write('\n')
    data.write(b + f + e)
    data.write('\n')
    data.write(b + f + f)
    data.write('\n')
    data.write(b + f + g)
    data.write('\n')
    data.write(b + f + h)
    data.write('\n')
    data.write(b + f + i)
    data.write('\n')
    data.write(b + f + j)
    data.write('\n')
    data.write(b + g + a)
    data.write('\n')
    data.write(b + g + b)
    data.write('\n')
    data.write(b + g + c)
    data.write('\n')
    data.write(b + g + d)
    data.write('\n')
    data.write(b + g + e)
    data.write('\n')
    data.write(b + g + f)
    data.write('\n')
    data.write(b + g + g)
    data.write('\n')
    data.write(b + g + h)
    data.write('\n')
    data.write(b + g + i)
    data.write('\n')
    data.write(b + g + j)
    data.write('\n')
    data.write(b + h + a)
    data.write('\n')
    data.write(b + h + b)
    data.write('\n')
    data.write(a + b + c + d)
    data.write('\n')
    data.write(b + h + c)
    data.write('\n')
    data.write(b + h + d)
    data.write('\n')
    data.write(b + h + e)
    data.write('\n')
    data.write(b + h + f)
    data.write('\n')
    data.write(b + h + g)
    data.write('\n')
    data.write(b + h + h)
    data.write('\n')
    data.write(b + h + i)
    data.write('\n')
    data.write(b + h + j)
    data.write('\n')
    data.write(b + i + a)
    data.write('\n')
    data.write(b + i + b)
    data.write('\n')
    data.write(b + i + c)
    data.write('\n')
    data.write(b + i + d)
    data.write('\n')
    data.write(b + i + e)
    data.write('\n')
    data.write(b + i + f)
    data.write('\n')
    data.write(b + i + g)
    data.write('\n')
    data.write(b + i + h)
    data.write('\n')
    data.write(b + i + i)
    data.write('\n')
    data.write(b + i + j)
    data.write('\n')
    data.write(b + j + a)
    data.write('\n')
    data.write(b + j + b)
    data.write('\n')
    data.write(b + j + c)
    data.write('\n')
    data.write(b + j + d)
    data.write('\n')
    data.write(b + j + e)
    data.write('\n')
    data.write(b + j + f)
    data.write('\n')
    data.write(b + j + g)
    data.write('\n')
    data.write(b + j + h)
    data.write('\n')
    data.write(b + j + i)
    data.write('\n')
    data.write(b + j + j)
    data.write('\n')
    data.write(c + a + b)
    data.write('\n')
    data.write(c + a + c)
    data.write('\n')
    data.write(c + a + d)
    data.write('\n')
    data.write(c + a + e)
    data.write('\n')
    data.write(c + a + f)
    data.write('\n')
    data.write(c + a + g)
    data.write('\n')
    data.write(c + a + h)
    data.write('\n')
    data.write(c + a + i)
    data.write('\n')
    data.write(c + a + j)
    data.write('\n')
    data.write(c + b + a)
    data.write('\n')
    data.write(c + b + b)
    data.write('\n')
    data.write(c + b + c)
    data.write('\n')
    data.write(c + b + d)
    data.write('\n')
    data.write(c + b + e)
    data.write('\n')
    data.write(c + b + f)
    data.write('\n')
    data.write(c + b + g)
    data.write('\n')
    data.write(c + b + h)
    data.write('\n')
    data.write(c + b + i)
    data.write('\n')
    data.write(c + b + j)
    data.write('\n')
    data.write(c + c + a)
    data.write('\n')
    data.write(c + c + b)
    data.write('\n')
    data.write(c + c + c)
    data.write('\n')
    data.write(c + c + d)
    data.write('\n')
    data.write(c + c + e)
    data.write('\n')
    data.write(c + c + f)
    data.write('\n')
    data.write(c + c + g)
    data.write('\n')
    data.write(c + c + h)
    data.write('\n')
    data.write(c + c + i)
    data.write('\n')
    data.write(c + c + j)
    data.write('\n')
    data.write(c + d + a)
    data.write('\n')
    data.write(c + d + b)
    data.write('\n')
    data.write(c + d + c)
    data.write('\n')
    data.write(c + d + d)
    data.write('\n')
    data.write(c + d + e)
    data.write('\n')
    data.write(c + d + f)
    data.write('\n')
    data.write(c + d + g)
    data.write('\n')
    data.write(c + d + h)
    data.write('\n')
    data.write(c + d + i)
    data.write('\n')
    data.write(c + d + j)
    data.write('\n')
    data.write(c + e + a)
    data.write('\n')
    data.write(c + e + b)
    data.write('\n')
    data.write(c + e + c)
    data.write('\n')
    data.write(c + e + d)
    data.write('\n')
    data.write(c + e + e)
    data.write('\n')
    data.write(c + e + f)
    data.write('\n')
    data.write(c + e + g)
    data.write('\n')
    data.write(c + e + h)
    data.write('\n')
    data.write(c + e + i)
    data.write('\n')
    data.write(c + e + j)
    data.write('\n')
    data.write(c + f + a)
    data.write('\n')
    data.write(c + f + b)
    data.write('\n')
    data.write(c + f + c)
    data.write('\n')
    data.write(c + f + d)
    data.write('\n')
    data.write(c + f + e)
    data.write('\n')
    data.write(c + f + f)
    data.write('\n')
    data.write(c + f + g)
    data.write('\n')
    data.write(c + f + h)
    data.write('\n')
    data.write(c + f + i)
    data.write('\n')
    data.write(c + f + j)
    data.write('\n')
    data.write(c + g + a)
    data.write('\n')
    data.write(c + g + b)
    data.write('\n')
    data.write(c + g + c)
    data.write('\n')
    data.write(c + g + d)
    data.write('\n')
    data.write(c + g + e)
    data.write('\n')
    data.write(c + g + f)
    data.write('\n')
    data.write(c + g + g)
    data.write('\n')
    data.write(c + g + h)
    data.write('\n')
    data.write(c + g + i)
    data.write('\n')
    data.write(c + g + j)
    data.write('\n')
    data.write(c + h + a)
    data.write('\n')
    data.write(c + h + b)
    data.write('\n')
    data.write(c + h + c)
    data.write('\n')
    data.write(c + h + d)
    data.write('\n')
    data.write(c + h + e)
    data.write('\n')
    data.write(c + h + f)
    data.write('\n')
    data.write(c + h + g)
    data.write('\n')
    data.write(c + h + h)
    data.write('\n')
    data.write(c + h + i)
    data.write('\n')
    data.write(c + h + j)
    data.write('\n')
    data.write(c + i + a)
    data.write('\n')
    data.write(c + i + b)
    data.write('\n')
    data.write(c + i + c)
    data.write('\n')
    data.write(c + i + d)
    data.write('\n')
    data.write(c + i + e)
    data.write('\n')
    data.write(c + i + f)
    data.write('\n')
    data.write(c + i + g)
    data.write('\n')
    data.write(c + i + h)
    data.write('\n')
    data.write(c + i + i)
    data.write('\n')
    data.write(c + i + j)
    data.write('\n')
    data.write(c + j + a)
    data.write('\n')
    data.write(c + j + b)
    data.write('\n')
    data.write(c + j + c)
    data.write('\n')
    data.write(c + j + d)
    data.write('\n')
    data.write(c + j + e)
    data.write('\n')
    data.write(c + j + f)
    data.write('\n')
    data.write(c + j + g)
    data.write('\n')
    data.write(c + j + h)
    data.write('\n')
    data.write(c + j + i)
    data.write('\n')
    data.write(c + j + j)
    data.write('\n')
    data.write(d + a + b)
    data.write('\n')
    data.write(d + a + c)
    data.write('\n')
    data.write(d + a + d)
    data.write('\n')
    data.write(d + a + e)
    data.write('\n')
    data.write(d + a + f)
    data.write('\n')
    data.write(d + a + g)
    data.write('\n')
    data.write(d + a + h)
    data.write('\n')
    data.write(d + a + i)
    data.write('\n')
    data.write(d + a + j)
    data.write('\n')
    data.write(d + b + a)
    data.write('\n')
    data.write(d + b + b)
    data.write('\n')
    data.write(d + b + c)
    data.write('\n')
    data.write(d + b + d)
    data.write('\n')
    data.write(d + b + e)
    data.write('\n')
    data.write(d + b + f)
    data.write('\n')
    data.write(d + b + g)
    data.write('\n')
    data.write(d + b + h)
    data.write('\n')
    data.write(d + b + i)
    data.write('\n')
    data.write(d + b + j)
    data.write('\n')
    data.write(d + c + a)
    data.write('\n')
    data.write(d + c + b)
    data.write('\n')
    data.write(d + c + c)
    data.write('\n')
    data.write(d + c + d)
    data.write('\n')
    data.write(d + c + e)
    data.write('\n')
    data.write(d + c + f)
    data.write('\n')
    data.write(d + c + g)
    data.write('\n')
    data.write(d + c + h)
    data.write('\n')
    data.write(d + c + i)
    data.write('\n')
    data.write(d + c + j)
    data.write('\n')
    data.write(d + d + a)
    data.write('\n')
    data.write(d + d + b)
    data.write('\n')
    data.write(d + d + c)
    data.write('\n')
    data.write(d + d + d)
    data.write('\n')
    data.write(d + d + e)
    data.write('\n')
    data.write(d + d + f)
    data.write('\n')
    data.write(d + d + g)
    data.write('\n')
    data.write(d + d + h)
    data.write('\n')
    data.write(d + d + i)
    data.write('\n')
    data.write(d + d + j)
    data.write('\n')
    data.write(d + e + a)
    data.write('\n')
    data.write(d + e + b)
    data.write('\n')
    data.write(d + e + c)
    data.write('\n')
    data.write(d + e + d)
    data.write('\n')
    data.write(d + e + e)
    data.write('\n')
    data.write(d + e + f)
    data.write('\n')
    data.write(d + e + g)
    data.write('\n')
    data.write(d + e + h)
    data.write('\n')
    data.write(d + e + i)
    data.write('\n')
    data.write(d + e + j)
    data.write('\n')
    data.write(d + f + a)
    data.write('\n')
    data.write(d + f + b)
    data.write('\n')
    data.write(d + f + c)
    data.write('\n')
    data.write(d + f + d)
    data.write('\n')
    data.write(d + f + e)
    data.write('\n')
    data.write(d + f + f)
    data.write('\n')
    data.write(d + f + g)
    data.write('\n')
    data.write(d + f + h)
    data.write('\n')
    data.write(d + f + i)
    data.write('\n')
    data.write(d + f + j)
    data.write('\n')
    data.write(d + g + a)
    data.write('\n')
    data.write(d + g + b)
    data.write('\n')
    data.write(d + g + c)
    data.write('\n')
    data.write(d + g + d)
    data.write('\n')
    data.write(d + g + e)
    data.write('\n')
    data.write(d + g + f)
    data.write('\n')
    data.write(d + g + g)
    data.write('\n')
    data.write(d + g + h)
    data.write('\n')
    data.write(d + g + i)
    data.write('\n')
    data.write(d + g + j)
    data.write('\n')
    data.write(d + h + a)
    data.write('\n')
    data.write(d + h + b)
    data.write('\n')
    data.write(d + h + c)
    data.write('\n')
    data.write(d + h + d)
    data.write('\n')
    data.write(d + h + e)
    data.write('\n')
    data.write(d + h + f)
    data.write('\n')
    data.write(d + h + g)
    data.write('\n')
    data.write(d + h + h)
    data.write('\n')
    data.write(d + h + i)
    data.write('\n')
    data.write(d + h + j)
    data.write('\n')
    data.write(d + i + a)
    data.write('\n')
    data.write(d + i + b)
    data.write('\n')
    data.write(d + i + c)
    data.write('\n')
    data.write(d + i + d)
    data.write('\n')
    data.write(d + i + e)
    data.write('\n')
    data.write(d + i + f)
    data.write('\n')
    data.write(d + i + g)
    data.write('\n')
    data.write(d + i + h)
    data.write('\n')
    data.write(d + i + i)
    data.write('\n')
    data.write(d + i + j)
    data.write('\n')
    data.write(d + j + a)
    data.write('\n')
    data.write(d + j + b)
    data.write('\n')
    data.write(d + j + c)
    data.write('\n')
    data.write(d + j + d)
    data.write('\n')
    data.write(d + j + e)
    data.write('\n')
    data.write(d + j + f)
    data.write('\n')
    data.write(d + j + g)
    data.write('\n')
    data.write(d + j + h)
    data.write('\n')
    data.write(d + j + i)
    data.write('\n')
    data.write(d + j + j)
    data.write('\n')
    data.write(e + a + b)
    data.write('\n')
    data.write(e + a + c)
    data.write('\n')
    data.write(e + a + d)
    data.write('\n')
    data.write(e + a + e)
    data.write('\n')
    data.write(e + a + f)
    data.write('\n')
    data.write(e + a + g)
    data.write('\n')
    data.write(e + a + h)
    data.write('\n')
    data.write(e + a + i)
    data.write('\n')
    data.write(e + a + j)
    data.write('\n')
    data.write(e + b + a)
    data.write('\n')
    data.write(e + b + b)
    data.write('\n')
    data.write(e + b + c)
    data.write('\n')
    data.write(e + b + d)
    data.write('\n')
    data.write(e + b + e)
    data.write('\n')
    data.write(e + b + f)
    data.write('\n')
    data.write(e + b + g)
    data.write('\n')
    data.write(e + b + h)
    data.write('\n')
    data.write(e + b + i)
    data.write('\n')
    data.write(e + b + j)
    data.write('\n')
    data.write(e + c + a)
    data.write('\n')
    data.write(e + c + b)
    data.write('\n')
    data.write(e + c + c)
    data.write('\n')
    data.write(e + c + d)
    data.write('\n')
    data.write(e + c + e)
    data.write('\n')
    data.write(e + c + f)
    data.write('\n')
    data.write(e + c + g)
    data.write('\n')
    data.write(e + c + h)
    data.write('\n')
    data.write(e + c + i)
    data.write('\n')
    data.write(e + c + j)
    data.write('\n')
    data.write(e + d + a)
    data.write('\n')
    data.write(e + d + b)
    data.write('\n')
    data.write(e + d + c)
    data.write('\n')
    data.write(e + d + d)
    data.write('\n')
    data.write(e + d + e)
    data.write('\n')
    data.write(e + d + f)
    data.write('\n')
    data.write(e + d + g)
    data.write('\n')
    data.write(e + d + h)
    data.write('\n')
    data.write(e + d + i)
    data.write('\n')
    data.write(e + d + j)
    data.write('\n')
    data.write(e + e + a)
    data.write('\n')
    data.write(e + e + b)
    data.write('\n')
    data.write(e + e + c)
    data.write('\n')
    data.write(e + e + d)
    data.write('\n')
    data.write(e + e + e)
    data.write('\n')
    data.write(e + e + f)
    data.write('\n')
    data.write(e + e + g)
    data.write('\n')
    data.write(e + e + h)
    data.write('\n')
    data.write(e + e + i)
    data.write('\n')
    data.write(e + e + j)
    data.write('\n')
    data.write(e + f + a)
    data.write('\n')
    data.write(e + f + b)
    data.write('\n')
    data.write(e + f + c)
    data.write('\n')
    data.write(e + f + d)
    data.write('\n')
    data.write(e + f + e)
    data.write('\n')
    data.write(e + f + f)
    data.write('\n')
    data.write(e + f + g)
    data.write('\n')
    data.write(e + f + h)
    data.write('\n')
    data.write(e + f + i)
    data.write('\n')
    data.write(e + f + j)
    data.write('\n')
    data.write(e + g + a)
    data.write('\n')
    data.write(e + g + b)
    data.write('\n')
    data.write(e + g + c)
    data.write('\n')
    data.write(e + g + d)
    data.write('\n')
    data.write(e + g + e)
    data.write('\n')
    data.write(e + g + f)
    data.write('\n')
    data.write(e + g + g)
    data.write('\n')
    data.write(e + g + h)
    data.write('\n')
    data.write(e + g + i)
    data.write('\n')
    data.write(e + g + j)
    data.write('\n')
    data.write(e + h + a)
    data.write('\n')
    data.write(e + h + b)
    data.write('\n')
    data.write(e + h + c)
    data.write('\n')
    data.write(e + h + d)
    data.write('\n')
    data.write(e + h + e)
    data.write('\n')
    data.write(e + h + f)
    data.write('\n')
    data.write(e + h + g)
    data.write('\n')
    data.write(e + h + h)
    data.write('\n')
    data.write(e + h + i)
    data.write('\n')
    data.write(e + h + j)
    data.write('\n')
    data.write(e + i + a)
    data.write('\n')
    data.write(e + i + b)
    data.write('\n')
    data.write(e + i + c)
    data.write('\n')
    data.write(e + i + d)
    data.write('\n')
    data.write(e + i + e)
    data.write('\n')
    data.write(e + i + f)
    data.write('\n')
    data.write(e + i + g)
    data.write('\n')
    data.write(e + i + h)
    data.write('\n')
    data.write(e + i + i)
    data.write('\n')
    data.write(e + i + j)
    data.write('\n')
    data.write(e + j + a)
    data.write('\n')
    data.write(e + j + b)
    data.write('\n')
    data.write(e + j + c)
    data.write('\n')
    data.write(e + j + d)
    data.write('\n')
    data.write(e + j + e)
    data.write('\n')
    data.write(e + j + f)
    data.write('\n')
    data.write(e + j + g)
    data.write('\n')
    data.write(e + j + h)
    data.write('\n')
    data.write(e + j + i)
    data.write('\n')
    data.write(e + j + j)
    data.write('\n')
    data.write(f + a + b)
    data.write('\n')
    data.write(f + a + c)
    data.write('\n')
    data.write(f + a + d)
    data.write('\n')
    data.write(f + a + e)
    data.write('\n')
    data.write(f + a + f)
    data.write('\n')
    data.write(f + a + g)
    data.write('\n')
    data.write(f + a + h)
    data.write('\n')
    data.write(f + a + i)
    data.write('\n')
    data.write(f + a + j)
    data.write('\n')
    data.write(f + b + a)
    data.write('\n')
    data.write(f + b + b)
    data.write('\n')
    data.write(f + b + c)
    data.write('\n')
    data.write(f + b + d)
    data.write('\n')
    data.write(f + b + e)
    data.write('\n')
    data.write(f + b + f)
    data.write('\n')
    data.write(f + b + g)
    data.write('\n')
    data.write(f + b + h)
    data.write('\n')
    data.write(f + b + i)
    data.write('\n')
    data.write(f + b + j)
    data.write('\n')
    data.write(f + c + a)
    data.write('\n')
    data.write(f + c + b)
    data.write('\n')
    data.write(f + c + c)
    data.write('\n')
    data.write(f + c + d)
    data.write('\n')
    data.write(f + c + e)
    data.write('\n')
    data.write(f + c + f)
    data.write('\n')
    data.write(f + c + g)
    data.write('\n')
    data.write(f + c + h)
    data.write('\n')
    data.write(f + c + i)
    data.write('\n')
    data.write(f + c + j)
    data.write('\n')
    data.write(f + d + a)
    data.write('\n')
    data.write(f + d + b)
    data.write('\n')
    data.write(f + d + c)
    data.write('\n')
    data.write(f + d + d)
    data.write('\n')
    data.write(f + d + e)
    data.write('\n')
    data.write(f + d + f)
    data.write('\n')
    data.write(f + d + g)
    data.write('\n')
    data.write(f + d + h)
    data.write('\n')
    data.write(f + d + i)
    data.write('\n')
    data.write(f + d + j)
    data.write('\n')
    data.write(f + e + a)
    data.write('\n')
    data.write(f + e + b)
    data.write('\n')
    data.write(f + e + c)
    data.write('\n')
    data.write(f + e + d)
    data.write('\n')
    data.write(f + e + e)
    data.write('\n')
    data.write(f + e + f)
    data.write('\n')
    data.write(f + e + g)
    data.write('\n')
    data.write(f + e + h)
    data.write('\n')
    data.write(f + e + i)
    data.write('\n')
    data.write(f + e + j)
    data.write('\n')
    data.write(f + f + a)
    data.write('\n')
    data.write(f + f + b)
    data.write('\n')
    data.write(f + f + c)
    data.write('\n')
    data.write(f + f + d)
    data.write('\n')
    data.write(f + f + e)
    data.write('\n')
    data.write(f + f + f)
    data.write('\n')
    data.write(f + f + g)
    data.write('\n')
    data.write(f + f + h)
    data.write('\n')
    data.write(f + f + i)
    data.write('\n')
    data.write(f + f + j)
    data.write('\n')
    data.write(f + g + a)
    data.write('\n')
    data.write(f + g + b)
    data.write('\n')
    data.write(f + g + c)
    data.write('\n')
    data.write(f + g + d)
    data.write('\n')
    data.write(f + g + e)
    data.write('\n')
    data.write(f + g + f)
    data.write('\n')
    data.write(f + g + g)
    data.write('\n')
    data.write(f + g + h)
    data.write('\n')
    data.write(f + g + i)
    data.write('\n')
    data.write(f + g + j)
    data.write('\n')
    data.write(f + h + a)
    data.write('\n')
    data.write(f + h + b)
    data.write('\n')
    data.write(f + h + c)
    data.write('\n')
    data.write(f + h + d)
    data.write('\n')
    data.write(f + h + e)
    data.write('\n')
    data.write(f + h + f)
    data.write('\n')
    data.write(f + h + g)
    data.write('\n')
    data.write(f + h + h)
    data.write('\n')
    data.write(f + h + i)
    data.write('\n')
    data.write(f + h + j)
    data.write('\n')
    data.write(f + i + a)
    data.write('\n')
    data.write(f + i + b)
    data.write('\n')
    data.write(f + i + c)
    data.write('\n')
    data.write(f + i + d)
    data.write('\n')
    data.write(f + i + e)
    data.write('\n')
    data.write(f + i + f)
    data.write('\n')
    data.write(f + i + g)
    data.write('\n')
    data.write(f + i + h)
    data.write('\n')
    data.write(f + i + i)
    data.write('\n')
    data.write(f + i + j)
    data.write('\n')
    data.write(f + j + a)
    data.write('\n')
    data.write(f + j + b)
    data.write('\n')
    data.write(f + j + c)
    data.write('\n')
    data.write(f + j + d)
    data.write('\n')
    data.write(f + j + e)
    data.write('\n')
    data.write(f + j + f)
    data.write('\n')
    data.write(f + j + g)
    data.write('\n')
    data.write(f + j + h)
    data.write('\n')
    data.write(f + j + i)
    data.write('\n')
    data.write(f + j + j)
    data.write('\n')
    data.write(g + a + b)
    data.write('\n')
    data.write(g + a + c)
    data.write('\n')
    data.write(g + a + d)
    data.write('\n')
    data.write(g + a + e)
    data.write('\n')
    data.write(g + a + f)
    data.write('\n')
    data.write(g + a + g)
    data.write('\n')
    data.write(g + a + h)
    data.write('\n')
    data.write(g + a + i)
    data.write('\n')
    data.write(g + a + j)
    data.write('\n')
    data.write(g + b + a)
    data.write('\n')
    data.write(g + b + b)
    data.write('\n')
    data.write(g + b + c)
    data.write('\n')
    data.write(g + b + d)
    data.write('\n')
    data.write(g + b + e)
    data.write('\n')
    data.write(g + b + f)
    data.write('\n')
    data.write(g + b + g)
    data.write('\n')
    data.write(g + b + h)
    data.write('\n')
    data.write(g + b + i)
    data.write('\n')
    data.write(g + b + j)
    data.write('\n')
    data.write(g + c + a)
    data.write('\n')
    data.write(g + c + b)
    data.write('\n')
    data.write(g + c + c)
    data.write('\n')
    data.write(g + c + d)
    data.write('\n')
    data.write(g + c + e)
    data.write('\n')
    data.write(g + c + f)
    data.write('\n')
    data.write(g + c + g)
    data.write('\n')
    data.write(g + b + g)
    data.write('\n')
    data.write(g + b + h + birthday)
    data.write('\n')
    data.write(g + b + i + birthday)
    data.write('\n')
    data.write(g + b + j + birthday)
    data.write('\n')
    data.write(g + c + a + birthday)
    data.write('\n')
    data.write(g + c + b + birthday)
    data.write('\n')
    data.write(g + c + c + birthday)
    data.write('\n')
    data.write(g + c + d + birthday)
    data.write('\n')
    data.write(g + c + e + birthday)
    data.write('\n')
    data.write(g + c + f + birthday)
    data.write('\n')
    data.write(g + c + g + birthday)
    data.write('\n')
    data.write(g + c + h)
    data.write('\n')
    data.write(g + c + i)
    data.write('\n')
    data.write(g + c + j)
    data.write('\n')
    data.write(g + d + a)
    data.write('\n')
    data.write(g + d + b)
    data.write('\n')
    data.write(g + d + c)
    data.write('\n')
    data.write(g + d + d)
    data.write('\n')
    data.write(g + d + e)
    data.write('\n')
    data.write(g + d + f)
    data.write('\n')
    data.write(g + d + g)
    data.write('\n')
    data.write(g + d + h)
    data.write('\n')
    data.write(g + d + i)
    data.write('\n')
    data.write(g + d + j)
    data.write('\n')
    data.write(g + e + a)
    data.write('\n')
    data.write(g + e + b)
    data.write('\n')
    data.write(g + e + c)
    data.write('\n')
    data.write(g + e + d)
    data.write('\n')
    data.write(g + e + e)
    data.write('\n')
    data.write(g + e + f)
    data.write('\n')
    data.write(g + e + g)
    data.write('\n')
    data.write(g + e + h)
    data.write('\n')
    data.write(g + e + i)
    data.write('\n')
    data.write(g + e + j)
    data.write('\n')
    data.write(g + f + a)
    data.write('\n')
    data.write(g + f + b)
    data.write('\n')
    data.write(g + f + c)
    data.write('\n')
    data.write(g + f + d)
    data.write('\n')
    data.write(g + f + e)
    data.write('\n')
    data.write(g + f + f)
    data.write('\n')
    data.write(g + f + g)
    data.write('\n')
    data.write(g + f + h)
    data.write('\n')
    data.write(g + f + i)
    data.write('\n')
    data.write(g + f + j)
    data.write('\n')
    data.write(g + g + a)
    data.write('\n')
    data.write(g + g + b)
    data.write('\n')
    data.write(g + g + c)
    data.write('\n')
    data.write(g + g + d)
    data.write('\n')
    data.write(g + g + e)
    data.write('\n')
    data.write(g + g + f)
    data.write('\n')
    data.write(g + g + g)
    data.write('\n')
    data.write(g + g + h)
    data.write('\n')
    data.write(g + g + i)
    data.write('\n')
    data.write(g + g + j)
    data.write('\n')
    data.write(g + h + a)
    data.write('\n')
    data.write(g + h + b)
    data.write('\n')
    data.write(g + h + c)
    data.write('\n')
    data.write(g + h + d)
    data.write('\n')
    data.write(g + h + e)
    data.write('\n')
    data.write(g + h + f)
    data.write('\n')
    data.write(g + h + g)
    data.write('\n')
    data.write(g + h + h)
    data.write('\n')
    data.write(g + h + i)
    data.write('\n')
    data.write(g + h + j)
    data.write('\n')
    data.write(g + i + a)
    data.write('\n')
    data.write(g + i + b)
    data.write('\n')
    data.write(g + i + c)
    data.write('\n')
    data.write(g + i + d)
    data.write('\n')
    data.write(g + i + e)
    data.write('\n')
    data.write(g + i + f)
    data.write('\n')
    data.write(g + i + g)
    data.write('\n')
    data.write(g + i + h)
    data.write('\n')
    data.write(g + i + i)
    data.write('\n')
    data.write(g + i + j)
    data.write('\n')
    data.write(g + j + a)
    data.write('\n')
    data.write(g + j + b)
    data.write('\n')
    data.write(g + j + c)
    data.write('\n')
    data.write(g + j + d)
    data.write('\n')
    data.write(g + j + e)
    data.write('\n')
    data.write(g + j + f)
    data.write('\n')
    data.write(g + j + g)
    data.write('\n')
    data.write(g + j + h)
    data.write('\n')
    data.write(g + j + i)
    data.write('\n')
    data.write(g + j + j)
    data.write('\n')
    data.write(h + a + b)
    data.write('\n')
    data.write(h + a + c)
    data.write('\n')
    data.write(h + a + d)
    data.write('\n')
    data.write(h + a + e)
    data.write('\n')
    data.write(h + a + f)
    data.write('\n')
    data.write(h + a + g)
    data.write('\n')
    data.write(h + a + h)
    data.write('\n')
    data.write(h + a + i)
    data.write('\n')
    data.write(h + a + j)
    data.write('\n')
    data.write(h + b + a)
    data.write('\n')
    data.write(h + b + b)
    data.write('\n')
    data.write(h + b + c)
    data.write('\n')
    data.write(h + b + d)
    data.write('\n')
    data.write(h + b + e)
    data.write('\n')
    data.write(h + b + f)
    data.write('\n')
    data.write(h + b + g)
    data.write('\n')
    data.write(h + b + h)
    data.write('\n')
    data.write(h + b + i)
    data.write('\n')
    data.write(h + b + j)
    data.write('\n')
    data.write(h + c + a)
    data.write('\n')
    data.write(h + c + b)
    data.write('\n')
    data.write(h + c + c)
    data.write('\n')
    data.write(h + c + d)
    data.write('\n')
    data.write(h + c + e)
    data.write('\n')
    data.write(h + c + f)
    data.write('\n')
    data.write(h + c + g)
    data.write('\n')
    data.write(h + c + h)
    data.write('\n')
    data.write(h + c + i)
    data.write('\n')
    data.write(h + c + j)
    data.write('\n')
    data.write(h + d + a)
    data.write('\n')
    data.write(h + d + b)
    data.write('\n')
    data.write(h + d + c)
    data.write('\n')
    data.write(h + d + d)
    data.write('\n')
    data.write(h + d + e)
    data.write('\n')
    data.write(h + d + f)
    data.write('\n')
    data.write(h + d + g)
    data.write('\n')
    data.write(h + d + h)
    data.write('\n')
    data.write(h + d + i)
    data.write('\n')
    data.write(h + d + j)
    data.write('\n')
    data.write(h + e + a)
    data.write('\n')
    data.write(h + e + b)
    data.write('\n')
    data.write(h + e + c)
    data.write('\n')
    data.write(h + e + d)
    data.write('\n')
    data.write(h + e + e)
    data.write('\n')
    data.write(h + e + f)
    data.write('\n')
    data.write(h + e + g)
    data.write('\n')
    data.write(h + e + h)
    data.write('\n')
    data.write(h + e + i)
    data.write('\n')
    data.write(h + e + j)
    data.write('\n')
    data.write(h + f + a)
    data.write('\n')
    data.write(h + f + b)
    data.write('\n')
    data.write(h + f + c)
    data.write('\n')
    data.write(h + f + d)
    data.write('\n')
    data.write(h + f + e)
    data.write('\n')
    data.write(h + f + f)
    data.write('\n')
    data.write(h + f + g)
    data.write('\n')
    data.write(h + f + h)
    data.write('\n')
    data.write(h + f + i)
    data.write('\n')
    data.write(h + f + j)
    data.write('\n')
    data.write(h + g + a)
    data.write('\n')
    data.write(h + g + b)
    data.write('\n')
    data.write(h + g + c)
    data.write('\n')
    data.write(h + g + d)
    data.write('\n')
    data.write(h + g + e)
    data.write('\n')
    data.write(h + g + f)
    data.write('\n')
    data.write(h + g + g)
    data.write('\n')
    data.write(h + g + h)
    data.write('\n')
    data.write(h + g + i)
    data.write('\n')
    data.write(h + g + j)
    data.write('\n')
    data.write(h + h + a)
    data.write('\n')
    data.write(h + h + b)
    data.write('\n')
    data.write(h + h + c)
    data.write('\n')
    data.write(h + h + d)
    data.write('\n')
    data.write(h + h + e)
    data.write('\n')
    data.write(h + h + f)
    data.write('\n')
    data.write(h + h + g)
    data.write('\n')
    data.write(h + h + h)
    data.write('\n')
    data.write(h + h + i)
    data.write('\n')
    data.write(h + h + j)
    data.write('\n')
    data.write(h + i + a)
    data.write('\n')
    data.write(h + i + b)
    data.write('\n')
    data.write(h + i + c)
    data.write('\n')
    data.write(h + i + d)
    data.write('\n')
    data.write(h + i + e)
    data.write('\n')
    data.write(h + i + f)
    data.write('\n')
    data.write(h + i + g)
    data.write('\n')
    data.write(h + i + h)
    data.write('\n')
    data.write(h + i + i)
    data.write('\n')
    data.write(h + i + j)
    data.write('\n')
    data.write(h + j + a)
    data.write('\n')
    data.write(h + j + b)
    data.write('\n')
    data.write(h + j + c)
    data.write('\n')
    data.write(h + j + d)
    data.write('\n')
    data.write(h + j + e)
    data.write('\n')
    data.write(h + j + f)
    data.write('\n')
    data.write(h + j + g)
    data.write('\n')
    data.write(h + j + h)
    data.write('\n')
    data.write(h + j + i)
    data.write('\n')
    data.write(h + j + j)
    data.write('\n')
    data.write(i + a + a)
    data.write('\n')
    data.write(i + a + b)
    data.write('\n')
    data.write(i + a + c)
    data.write('\n')
    data.write(i + a + d)
    data.write('\n')
    data.write(i + a + e)
    data.write('\n')
    data.write(i + a + f)
    data.write('\n')
    data.write(i + a + g)
    data.write('\n')
    data.write(i + a + h)
    data.write('\n')
    data.write(i + a + i)
    data.write('\n')
    data.write(i + a + j)
    data.write('\n')
    data.write(i + b + a)
    data.write('\n')
    data.write(i + b + b)
    data.write('\n')
    data.write(i + b + c)
    data.write('\n')
    data.write(i + b + d)
    data.write('\n')
    data.write(i + b + e)
    data.write('\n')
    data.write(i + b + f)
    data.write('\n')
    data.write(i + b + g)
    data.write('\n')
    data.write(i + b + h)
    data.write('\n')
    data.write(i + b + i)
    data.write('\n')
    data.write(i + b + j)
    data.write('\n')
    data.write(i + c + a)
    data.write('\n')
    data.write(i + c + b)
    data.write('\n')
    data.write(i + c + c)
    data.write('\n')
    data.write(i + c + d)
    data.write('\n')
    data.write(i + c + e)
    data.write('\n')
    data.write(i + c + f)
    data.write('\n')
    data.write(i + c + g)
    data.write('\n')
    data.write(i + c + h)
    data.write('\n')
    data.write(i + c + i)
    data.write('\n')
    data.write(i + c + j)
    data.write('\n')
    data.write(i + d + a)
    data.write('\n')
    data.write(i + d + b)
    data.write('\n')
    data.write(i + d + c)
    data.write('\n')
    data.write(i + d + d)
    data.write('\n')
    data.write(i + d + e)
    data.write('\n')
    data.write(i + d + f)
    data.write('\n')
    data.write(i + d + g)
    data.write('\n')
    data.write(i + d + h)
    data.write('\n')
    data.write(i + d + i)
    data.write('\n')
    data.write(i + d + j)
    data.write('\n')
    data.write(i + e + a)
    data.write('\n')
    data.write(i + e + b)
    data.write('\n')
    data.write(i + e + c)
    data.write('\n')
    data.write(i + e + d)
    data.write('\n')
    data.write(i + e + e)
    data.write('\n')
    data.write(i + e + f)
    data.write('\n')
    data.write(i + e + g)
    data.write('\n')
    data.write(i + e + h)
    data.write('\n')
    data.write(i + e + i)
    data.write('\n')
    data.write(i + e + j)
    data.write('\n')
    data.write(i + f + a)
    data.write('\n')
    data.write(i + f + b)
    data.write('\n')
    data.write(i + f + c)
    data.write('\n')
    data.write(i + f + d)
    data.write('\n')
    data.write(i + f + e)
    data.write('\n')
    data.write(i + f + f)
    data.write('\n')
    data.write(i + f + g)
    data.write('\n')
    data.write(i + f + h)
    data.write('\n')
    data.write(i + f + i)
    data.write('\n')
    data.write(i + f + j)
    data.write('\n')
    data.write(i + g + a)
    data.write('\n')
    data.write(i + g + b)
    data.write('\n')
    data.write(i + g + c)
    data.write('\n')
    data.write(i + g + d)
    data.write('\n')
    data.write(i + g + e)
    data.write('\n')
    data.write(i + g + f)
    data.write('\n')
    data.write(i + g + g)
    data.write('\n')
    data.write(i + g + h)
    data.write('\n')
    data.write(i + g + i)
    data.write('\n')
    data.write(i + g + j)
    data.write('\n')
    data.write(i + h + a)
    data.write('\n')
    data.write(i + h + b)
    data.write('\n')
    data.write(i + h + c)
    data.write('\n')
    data.write(i + h + d)
    data.write('\n')
    data.write(i + h + e)
    data.write('\n')
    data.write(i + h + f)
    data.write('\n')
    data.write(i + h + g)
    data.write('\n')
    data.write(i + h + h)
    data.write('\n')
    data.write(i + h + i)
    data.write('\n')
    data.write(i + h + j)
    data.write('\n')
    data.write(i + i + a)
    data.write('\n')
    data.write(i + i + b)
    data.write('\n')
    data.write(i + i + c)
    data.write('\n')
    data.write(i + i + d)
    data.write('\n')
    data.write(i + i + e)
    data.write('\n')
    data.write(i + i + f)
    data.write('\n')
    data.write(i + i + g)
    data.write('\n')
    data.write(i + i + h)
    data.write('\n')
    data.write(i + i + i)
    data.write('\n')
    data.write(i + i + j)
    data.write('\n')
    data.write(i + j + a)
    data.write('\n')
    data.write(i + j + b)
    data.write('\n')
    data.write(i + j + c)
    data.write('\n')
    data.write(i + j + d)
    data.write('\n')
    data.write(i + j + e)
    data.write('\n')
    data.write(i + j + f)
    data.write('\n')
    data.write(i + j + g)
    data.write('\n')
    data.write(i + j + h)
    data.write('\n')
    data.write(i + j + i)
    data.write('\n')
    data.write(i + j + j)
    data.write('\n')
    data.write(j + a + b)
    data.write('\n')
    data.write(j + a + c)
    data.write('\n')
    data.write(j + a + d)
    data.write('\n')
    data.write(j + a + e)
    data.write('\n')
    data.write(j + a + f)
    data.write('\n')
    data.write(j + a + g)
    data.write('\n')
    data.write(j + a + h)
    data.write('\n')
    data.write(j + a + i)
    data.write('\n')
    data.write(j + a + j)
    data.write('\n')
    data.write(j + b + a)
    data.write('\n')
    data.write(j + b + b)
    data.write('\n')
    data.write(j + b + c)
    data.write('\n')
    data.write(j + b + d)
    data.write('\n')
    data.write(j + b + e)
    data.write('\n')
    data.write(j + b + f)
    data.write('\n')
    data.write(j + b + g)
    data.write('\n')
    data.write(j + b + h)
    data.write('\n')
    data.write(j + b + i)
    data.write('\n')
    data.write(j + b + j)
    data.write('\n')
    data.write(j + c + a)
    data.write('\n')
    data.write(j + c + b)
    data.write('\n')
    data.write(j + c + c)
    data.write('\n')
    data.write(j + c + d)
    data.write('\n')
    data.write(j + c + e)
    data.write('\n')
    data.write(j + c + f)
    data.write('\n')
    data.write(j + c + g)
    data.write('\n')
    data.write(j + c + h)
    data.write('\n')
    data.write(j + c + i)
    data.write('\n')
    data.write(j + c + j)
    data.write('\n')
    data.write(j + d + a)
    data.write('\n')
    data.write(j + d + b)
    data.write('\n')
    data.write(j + d + c)
    data.write('\n')
    data.write(j + d + d)
    data.write('\n')
    data.write(j + d + e)
    data.write('\n')
    data.write(j + d + f)
    data.write('\n')
    data.write(j + d + g)
    data.write('\n')
    data.write(j + d + h)
    data.write('\n')
    data.write(j + d + i)
    data.write('\n')
    data.write(j + d + j)
    data.write('\n')
    data.write(j + e + a)
    data.write('\n')
    data.write(j + e + b)
    data.write('\n')
    data.write(j + e + c)
    data.write('\n')
    data.write(j + e + d)
    data.write('\n')
    data.write(j + e + e)
    data.write('\n')
    data.write(j + e + f)
    data.write('\n')
    data.write(j + e + g)
    data.write('\n')
    data.write(j + e + h)
    data.write('\n')
    data.write(j + e + i)
    data.write('\n')
    data.write(j + e + j)
    data.write('\n')
    data.write(j + f + a)
    data.write('\n')
    data.write(j + f + b)
    data.write('\n')
    data.write(j + f + c)
    data.write('\n')
    data.write(j + f + d)
    data.write('\n')
    data.write(j + f + e)
    data.write('\n')
    data.write(j + f + f)
    data.write('\n')
    data.write(j + f + g)
    data.write('\n')
    data.write(j + f + h)
    data.write('\n')
    data.write(j + f + i)
    data.write('\n')
    data.write(j + f + j)
    data.write('\n')
    data.write(j + g + a)
    data.write('\n')
    data.write(j + g + b)
    data.write('\n')
    data.write(j + g + c)
    data.write('\n')
    data.write(j + g + d)
    data.write('\n')
    data.write(j + g + e)
    data.write('\n')
    data.write(j + g + f)
    data.write('\n')
    data.write(j + g + g)
    data.write('\n')
    data.write(j + g + h)
    data.write('\n')
    data.write(j + g + i)
    data.write('\n')
    data.write(j + g + j)
    data.write('\n')
    data.write(j + h + a)
    data.write('\n')
    data.write(j + h + b)
    data.write('\n')
    data.write(j + h + c)
    data.write('\n')
    data.write(j + h + d)
    data.write('\n')
    data.write(j + h + e)
    data.write('\n')
    data.write(j + h + f)
    data.write('\n')
    data.write(j + h + g)
    data.write('\n')
    data.write(j + h + h)
    data.write('\n')
    data.write(j + h + i)
    data.write('\n')
    data.write(j + h + j)
    data.write('\n')
    data.write(j + i + a)
    data.write('\n')
    data.write(j + i + b)
    data.write('\n')
    data.write(j + i + c)
    data.write('\n')
    data.write(j + i + d)
    data.write('\n')
    data.write(j + i + e)
    data.write('\n')
    data.write(j + i + f)
    data.write('\n')
    data.write(j + i + g)
    data.write('\n')
    data.write(j + i + h)
    data.write('\n')
    data.write(j + i + i)
    data.write('\n')
    data.write(j + i + j)
    data.write('\n')
    data.write(j + j + a)
    data.write('\n')
    data.write(j + j + b)
    data.write('\n')
    data.write(j + j + c)
    data.write('\n')
    data.write(j + j + d)
    data.write('\n')
    data.write(j + j + e)
    data.write('\n')
    data.write(j + j + f)
    data.write('\n')
    data.write(j + j + g)
    data.write('\n')
    data.write(j + j + h)
    data.write('\n')
    data.write(j + j + i)
    data.write('\n')
    data.write(j + j + j)
    data.write('\n')
    data.write(g + i + j)
    data.write('\n')
    data.write(h + i + j)
    data.write('\n')
    extra_words = input('->[+] Listene en çok kullanılan parolalar eklensin mi [E veya H] : ').upper()
    if extra_words == "E":
        data = open(victimName + '.txt','a+')
        data.write('123456')
        data.write('\n')
        data.write('123456789')
        data.write('\n')
        data.write('qwerty')
        data.write('\n')
        data.write('12345678')
        data.write('\n')
        data.write('111111')
        data.write('\n')
        data.write('1234567890')
        data.write('\n')
        data.write('1234567')
        data.write('\n')
        data.write('password')
        data.write('\n')
        data.write('123123')
        data.write('\n')
        data.write('987654321')
        data.write('\n')
        data.write('qwertyuiop')
        data.write('\n')
        data.write('mynoob')
        data.write('\n')
        data.write('123321')
        data.write('\n')
        data.write('666666')
        data.write('\n')
        data.write('18atcskd2w')
        data.write('\n')
        data.write('7777777')
        data.write('\n')
        data.write('1q2w3e4r')
        data.write('\n')
        data.write('654321')
        data.write('\n')
        data.write('555555')
        data.write('\n')
        data.write('3rjs1la7qe')
        data.write('\n')
        data.write('google')
        data.write('\n')
        data.write('1q2w3e4r5t')
        data.write('\n')
        data.write('123qwe')
        data.write('\n')
        data.write('zxcvbnm')
        data.write('\n')
        data.write('1q2w3e')
        data.write('\n')
        data.write('Abc123')
        data.write('\n')
        print ("\n[+] Eklendi!")
        data.close()
    else:
        print ("\n[-] Eklenmedi!")
        data.close()
        ### And ends here ###
    print("\t\n" + victimName + ".txt","dosyası",os.getcwd(),"dizinine kaydedildi!")
    input()
except KeyboardInterrupt:
    print('\n[-] İşlem İptal Edildi')
    if 'victimName' in locals():   
        data.close()
        os.remove(victimName+".txt")
    input()
